services:
  postgres:
    image: postgres:16
    container_name: autoflex_postgres_test
    environment:
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USER_TEST}
      POSTGRES_PASSWORD: ${DB_PASS_TEST}
    ports:
      - '${DB_PORT_TEST}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER_TEST} -d ${DB_NAME_TEST}']
      interval: 5s
      timeout: 5s
      retries: 10
